events {
   worker_connections 4096;
   use epoll;
   multi_accept on;
}

http {
   server {
      listen 80;
      server_name gekuio.ru www.gekuio.ru;
      return 301 https://$host$request_uri;
   }

   server {
      listen 443 ssl;

      server_name gekuio.ru www.gekuio.ru;
      ssl_certificate /etc/ssl/gekuio.ru/gekuio.crt;
      ssl_certificate_key /etc/ssl/gekuio.ru/gekuio.key;

      location /api/ {
         proxy_pass http://backend:3001/;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
      }

      location /ws/ {
         proxy_pass http://backend:3001/socket.io/admin/;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection 'upgrade';
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_read_timeout 86400;
         proxy_send_timeout 86400;
      }

      location / {
         proxy_pass http://frontend:3000/;
         proxy_http_version 1.1;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection 'upgrade';
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
         proxy_cache_bypass $http_upgrade;
      }
   }
}